use_frameworks!
target 'WhatEat' do
  
pod 'Alamofire'
pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'FDFullscreenPopGesture', '1.1'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'HandyJSON', '~> 5.0.0'
pod 'WCDB.swift'
pod 'Bugly'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Google-Mobile-Ads-SDK'
pod 'YYText'
pod 'SwiftyJSON', '~> 4.0'
pod 'IQKeyboardManagerSwift'

end
